
const express = require('express');
const router = express.Router();
const { loggerWin } = require('../utils/expressWinston.js')

/* GET home page. */
router.get('/api/appraiseinfo', (req, res, next)=> {
  res.json({
    "success":true,
    "data":[
    
      {
        "level":0,
        "id":0,
        "proname":"Apple iPhone XR",
        "appraisevolume":74,
        "goodappraiseratio":98,
        "goodappraisenum":73,
        "neuappraisenum":3300,
        "badappraisenum":3600,
        "momentsnum":4.4,
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳",
            "commentstars":5,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简陋，拿起来摇晃，只听到里面东西在响，这也太简陋了。再说说外观，之前已经买了一台荣耀play给儿子用，对这个刘海屏也有所了解，感觉那个刘海不怎么喜欢，全面屏总体外观比以前用的6X要好看多了，（老婆还在用另一台6X）但就是屏幕太长，大拇指够不到顶部，也不好抓，后面必须得粘一个指环扣，不然单手真的不好拿。再说说这个处理器和反应速度，真的是一分钱一分货，我不玩游戏，但是打开某些软件或文件总体来说就是卡，慢，半天还在转圈圈，在~空间里同时上传三个视频到说说，直接就不动了，关闭软件重新打开时那些视频只能重新再上传了，不能接续，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了",
            "commentstars":2,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气",
            "commentstars":1,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友",
            "commentstars":4,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
        
      },
      {
        "level":0,
        "id":1,
        "proname":"Apple iPhone X",
        "appraisevolume":"125",
        "appraisevolume":"",
        "goodappraiseratio":"99%",
        "goodappraisenum":"121",
        "neuappraisenum":"3300",
        "badappraisenum":"3600",
        "momentsnum":"6.4",
        "commentinfo": [
          {
            "nickname":"运来了",
            "commentstars":5,
            "commendate":"2019-1-11",
            "commentcontent":"用了三个星期，来说说感受，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了没有",
            "commentstars":4,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气2",
            "commentstars":5,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友2",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":2,
        "productitemname":"苹果",
        "proname":"Apple iPhone 8 Plus",
        "appraisevolume":"195",
        "appraisevolume":"",
        "goodappraiseratio":"98%",
        "goodappraisenum":"191",
        "neuappraisenum":"5390",
        "badappraisenum":"4300",
        "momentsnum":"11.4",
        "commentinfo": [
          {
            "nickname":"运来了3",
            "commentstars":3,
            "commendate":"2019-1-11",
            "commentcontent":"运来了2用了三个星期，来说说感受，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友6",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"大灰狼的小朋友23-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
  
      },
      {
        "level":0,
        "id":3,
        "productitemname":"苹果",
        "proname":"Apple iPhone Xs Max",
        "appraisevolume":"35",
        "appraisevolume":"",
        "goodappraiseratio":"97%",
        "goodappraisenum":"33",
        "neuappraisenum":"1390",
        "badappraisenum":"3300",
        "momentsnum":"12.4",
        "commentinfo": [
          {
            "nickname":"运来了3",
            "commentstars":3,
            "commendate":"2019-1-11",
            "commentcontent":"运来了2用了三个星期，来说说感受，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了没有4",
            "commentstars":5,
            "commendate":"2017-12-11",
            "commentcontent":"系统坏了没有21-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气5",
            "commentstars":5,
            "commendate":"2018-11-11",
            "commentcontent":"机房的天气22-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友6",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"大灰狼的小朋友23-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":4,
        "productitemname":"苹果",
        "proname":"Apple iPhone XS",
        "appraisevolume":"31",
        "appraisevolume":"",
        "goodappraiseratio":"98%",
        "goodappraisenum":"30",
        "neuappraisenum":"1390",
        "badappraisenum":"1300",
        "momentsnum":"12.4",
        "commentinfo": [
          {
            "nickname":"系统坏了没有4",
            "commentstars":3,
            "commendate":"2017-12-11",
            "commentcontent":"系统坏了没有21-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气5",
            "commentstars":5,
            "commendate":"2018-11-11",
            "commentcontent":"机房的天气22-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]	
        
      },
      {
        "level":0,
        "id":5,
        "productitemname":"华为",
        "proname":"华为 HUAWEI Mate 20",
        "appraisevolume":"109",
        "goodappraiseratio":"98%",
        "goodappraisenum":"108",
        "neuappraisenum":"6500",
        "badappraisenum":"608",
        "momentsnum":"64",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳",
            "commentstars":5,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简陋，拿起来摇晃，只听到里面东西在响，这也太简陋了。再说说外观，之前已经买了一台荣耀play给儿子用，对这个刘海屏也有所了解，感觉那个刘海不怎么喜欢，全面屏总体外观比以前用的6X要好看多了，（老婆还在用另一台6X）但就是屏幕太长，大拇指够不到顶部，也不好抓，后面必须得粘一个指环扣，不然单手真的不好拿。再说说这个处理器和反应速度，真的是一分钱一分货，我不玩游戏，但是打开某些软件或文件总体来说就是卡，慢，半天还在转圈圈，在~空间里同时上传三个视频到说说，直接就不动了，关闭软件重新打开时那些视频只能重新再上传了，不能接续，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了",
            "commentstars":5,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气",
            "commentstars":3,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":6,
        "productitemname":"华为",
        "proname":"华为 HUAWEI Mate 20 Pro",
        "appraisevolume":"35",
        "goodappraiseratio":"98%",
        "goodappraisenum":"34",
        "neuappraisenum":"300",
        "badappraisenum":"1600",
        "momentsnum":"6",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳",
            "commentstars":5,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简陋，拿起来摇晃，只听到里面东西在响，这也太简陋了。再说说外观，之前已经买了一台荣耀play给儿子用，对这个刘海屏也有所了解，凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了",
            "commentstars":3,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气",
            "commentstars":1,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":7,
        "productitemname":"华为",
        "proname":"华为 HUAWEI 畅享9 Plus",
        "appraisevolume":"104",
        "goodappraiseratio":"98%",
        "goodappraisenum":"100",
        "neuappraisenum":"300",
        "badappraisenum":"600",
        "momentsnum":"90",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳",
            "commentstars":1,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了",
            "commentstars":5,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气",
            "commentstars":2,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":8,
        "productitemname":"华为",
        "proname":"华为 HUAWEI P20",
        "appraisevolume":"94",
        "goodappraiseratio":"99%",
        "goodappraisenum":"93",
        "neuappraisenum":"300",
        "badappraisenum":"30",
        "momentsnum":"",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳",
            "commentstars":5,
            "commendate":"2017-10-11",
            "commentcontent":"了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了",
            "commentstars":5,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气",
            "commentstars":4,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友",
            "commentstars":5,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":9,
        "productitemname":"华为",
        "proname":"华为新品 HUAWEI nova 4",
        "appraisevolume":"54",
        "goodappraiseratio":"98%",
        "goodappraisenum":"53",
        "neuappraisenum":"6300",
        "badappraisenum":"300",
        "momentsnum":"44",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳",
            "commentstars":5,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简陋，拿起来摇晃，只听到里面东西在响，这也太简陋了。再说说外观，之前已经买了一台荣耀play给儿子用，对这个刘海屏也有所了解，感觉那个刘海不怎么喜欢，全面屏总体外观比以前用的6X要好看多了，（老婆还在用另一台6X）但就是屏幕太长，大拇指够不到顶部，也不好抓，圈圈，在~空间里同时上传三个视频到说说，直接就不动了，关闭软件重新打开时那些视频只能重新再上传了，不能接续，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"系统坏了",
            "commentstars":4,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气",
            "commentstars":5,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友",
            "commentstars":2,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":10,
        "productitemname":"耳机",
        "proname":"漫步者（EDIFIER）W200BT经典版",
        "appraisevolume":"0",
        "goodappraiseratio":"0%",
        "goodappraisenum":"0",
        "neuappraisenum":"0",
        "badappraisenum":"0",
        "momentsnum":"0",
        "commentinfo": [
          
            
        ]
      },
      {
        "level":0,
        "id":11,
        "productitemname":"耳机",
        "proname":"Bose QuietControl 30",
        "appraisevolume":"4",
        "goodappraiseratio":"100%",
        "goodappraisenum":"4",
        "neuappraisenum":"",
        "badappraisenum":"",
        "momentsnum":"",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳11",
            "commentstars":2,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简陋，拿起来摇晃，只听到里面东西在响，这也太简陋了。再说说外观，之前已经买了一台荣耀play给儿子用，对这个刘海屏也了，不能接续，这能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":12,
        "productitemname":"耳机",
        "proname":"Apple  AirPods 蓝牙无线耳机",
        "appraisevolume":"74",
        "goodappraiseratio":"99%",
        "goodappraisenum":"74",
        "neuappraisenum":"",
        "badappraisenum":"",
        "momentsnum":"44",
        "commentinfo": [
          {
            "nickname":"系统坏了",
            "commentstars":5,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":13,
        "productitemname":"耳机",
        "proname":"三星（SAMSUNG）Gear IconX 2018升级款",
        "appraisevolume":"40",
        "goodappraiseratio":"99%",
        "goodappraisenum":"39",
        "neuappraisenum":"1",
        "badappraisenum":"",
        "momentsnum":"4",
        "commentinfo": [
          {
            "nickname":"系统坏了14",
            "commentstars":5,
            "commendate":"2017-12-11",
            "commentcontent":"1-关于信号，东西到之前看到很多说信号问题的，到了后，在室外和一般地方都是满格，电梯两格，在之前我安卓手机信号也不怎么好的地方基本上两三格。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"机房的天气14",
            "commentstars":5,
            "commendate":"2018-11-11",
            "commentcontent":"2-续航，我偶尔打游戏，刷~，充一次电基本用一天。充满基本要两三个小时",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          },
          {
            "nickname":"大灰狼的小朋友13",
            "commentstars":4,
            "commendate":"2018-12-11",
            "commentcontent":"3-厚度重量，比我在网上看到各种消息后想象的厚度与重量轻。我觉得能接受，一般，也不是很重，但是带上壳子后觉得他重了。还是算比较厚的了。4-5399入，果然是买之前想他再降价，买了后就希望不要再将了，看到涨价感到一丝丝的庆幸。之前在考虑这个时候该不该买。5-黑边确实比较宽，但是我耍手机又不看黑边，所以我对于黑边还是比较无所谓的。买的白色，但是到了后个人觉得黑色应该要更好看些。以上。",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
        ]
      },
      {
        "level":0,
        "id":14,
        "productitemname":"耳机",
        "proname":"索尼（SONY）WI-1000X Hi-Res颈挂式",
        "appraisevolume":"40",
        "goodappraiseratio":"99%",
        "goodappraisenum":"73",
        "neuappraisenum":"40",
        "badappraisenum":"",
        "momentsnum":"4",
        "commentinfo": [
          {
            "nickname":"红高粱的小太阳14",
            "commentstars":4,
            "commendate":"2017-10-11",
            "commentcontent":"用了三个星期，来说说感受：首先是送货速度快，晚上下单，第二天就到了，京东自营就是快。第二个是包装，这个只能给三分了，看着很简陋，拿起来摇晃，只听到里面东西在响，这也太简陋了。再说说外观，之前已经买了一台荣耀play给儿子用，对这个刘海屏也有所了解，感觉那个刘海不怎么喜欢，全面屏总体外观比以前用的6X要好看多了，（老婆还在用另一台6X）但就是屏幕太长，大拇指够不到顶部，也不好抓，后面必须得粘一个指环扣，不然单手真的不好拿。再说说这个处理器和反应速度，真的是一分钱一分货，我不玩游戏，但是打开某些软件或文件总体来说就是卡，慢，半天还在转圈圈，在~空间里同时上传三个视频到说说，直接就不动了，关闭软件重新打开时那些视频只能重新再上传了，不能接续，这个处理器只能说凑合着吧，跟荣耀play的970还是有很大差距。再说说这个网络，感觉比之前我用的6❌还差，进到卫生间里就没有WiFi和移动网络了，而且也不能自动切换WiFi信号，我以前用的华为荣耀手机都没这种情况。再说说拍照，这个优点就是夜拍了，夜间用AI模式拍出来的照片很清晰，这个我很喜欢，缺点就是慢，要拿好久才能拍出来，而且我发现一个问题就是拍~",
            "imgurl1":"",
            "imgurl2":"",
            "imgurl3":"",
            "imgurl4":"",
            "imgurl5":""
          }
          
        ]
      }
    ]
  })
 
});

module.exports = router;

