/* GET cartlist page. */
var express = require('express');
var router = express.Router();


const  { RedisGetdata } = require('../db/redis/redisoperation.js')
const {  
    CartListAdd,
    CartListFind,
    CartListaggfind 
} = require('../db/mongodb/userinfoSchema.js')
const { loggerWin } = require('../utils/expressWinston.js')

router.get('/api/cartinfo',async (req, res, next)=> {

    // let m = await RedisGetdata()
    // console.log('req.body',req.body)
    console.log('session',req.session.username)
 
    loggerWin.info(`${req.method}--${req.url}--${req.headers['user-agent']}`)
   res.json(
    {
      "success":true,
      "data":{
        "cartproinfo": {
          "selfsell":[
            {
              "id": 0,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s168x168_jfs/t20029/62/570986436/272562/1f3b66fe/5afd3d77N426b7b3b.jpg!q70.dpg.webp",
              "producbrand": "惠普(HP)",
              "producmodel": "EliteBook 735G5",
              "produsize": "13.3英寸",
              "productname": "轻薄笔记本电脑",
              "producotherinfo":"锐龙5 PRO 2500U 8G 256SSD Win10 100%sRGB一年上门）",
              "productcolor":"",
              "manufacutuer":"",
              "productbrief": "惠普（HP）EliteBook 735G5 13.3英寸轻薄笔记本电脑（锐龙5 PRO 2500U 8G 256SSD Win10 100%sRGB一年上门）",
              "proselectiontext":"2.185kg/件，【13.3英寸】，【R5 8G 256GSSD 高色域屏】",
              "payinfo":"白条支付3期免息",
              "currency":"￥",
              "uprice":"4999",
              "sevice":"选择增值服务",
              "promotioninf":""
    
            },
            {
              "id": 2,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s168x168_jfs/t10675/253/1344769770/66891/92d54ca4/59df2e7fN86c99a27.jpg!q70.dpg.webp",
              "producbrand": "苹果(APPLE)",
              "producmodel": "Apple iPhone X",
              "produsize": "64G",
              "productname": "轻薄笔记本电脑",
              "productcolor":"深空灰色",
              "producotherinfo":"移动联通电信4G手机",
              "manufacutuer":"",
              "productbrief": "Apple iPhone X (A1865) 64GB 深空灰色 移动联通电信4G手机",
              "proselectiontext":"0.435kg/件，深空灰色，公开版",
              "payinfo":"白条支付3期免息",
              "currency":"￥",
              "uprice":"6349",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":""
            },
            {
              "id": 3,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s168x168_jfs/t1/205/4/14447/185505/5bdab250E4f0ea9d3/2bb3ddfe50771599.jpg!q70.dpg.webp",
              "producbrand": "福临门",
              "producmodel": "葵花籽清香食用植物调和油",
              "produsize": "5L",
              "productname": "葵花籽油",
              "productcolor":"",
              "producotherinfo":" 中粮出品",
              "manufacutuer":"",
              "productbrief": "福临门 食用油 葵花籽清香食用植物调和油5L 中粮出品",
              "proselectiontext":"4.73kg/件，葵花籽原香食用调和油5L",
              "payinfo":"白条支付3期免息",
              "currency":"￥",
              "uprice":"39.9",
              "sevice":"[礼品购]礼品服务",
              "promotioninf":"满两件总价9.5折"
            },
            {
              "id": 4,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t1/5064/31/3461/142209/5b997c0eE8b26d23e/8788a4743af36f36.jpg!q70.dpg.webp",
              "producbrand": "苹果(APPLE)",
              "producmodel": "Apple iPhone XS",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "Apple iPhone XS (A2100) 64GB 深空灰色 移动联通电信4G手机",
              "proselectiontext":"0.43kg/件，深空灰色，公开版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"7899",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":"购买一件可优惠换购热销商品"
            },
            {
              "id": 5,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t1/3/15/4536/138660/5b997bf8Ed72ebce7/819dcf182d743897.jpg!q70.dpg.webp",
              "producbrand": "苹果(APPLE)",
              "producmodel": "Apple iPhone Xs Max",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "Apple iPhone XS Max (A2104) 256GB 深空灰色 移动联通电信4G手机 双卡双待",
              "proselectiontext":"0.49kg/件，深空灰色，公开版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"9999",
              "sevice":"选择增值服务",
              "promotioninf":"购买一件可优惠换购热销商品"
            },
            {
              "id": 6,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t1/3405/18/3537/69901/5b997c0aE5dc8ed9f/a2c208410ae84d1f.jpg!q70.dpg.webp",
              "producbrand": "苹果(APPLE)",
              "producmodel": "Apple iPhone XR",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "Apple iPhone XR (A2108) 128GB 黑色 移动联通电信4G手机 双卡双待",
              "proselectiontext":"0.46kg/件，黑色，公开版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"5999",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":"购买一件可优惠换购热销商品"
            },
            {
              "id": 7,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t10675/253/1344769770/66891/92d54ca4/59df2e7fN86c99a27.jpg!q70.dpg.webp",
              "producbrand": "苹果(APPLE)",
              "producmodel": "Apple iPhone 8 Plus",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "Apple iPhone 8 Plus (A1864) 64GB 深空灰色 移动联通电信4G手机",
              "proselectiontext":"0.48kg/件,深空灰色，公开版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"6249",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":""
            },
            {
              "id": 8,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/n2/s240x240_jfs/t1/27659/3/1138/118885/5c0f8c5dE56e8df2b/028857f503e52df0.jpg!q70.jpg",
              "producbrand": "HUAWEI",
              "producmodel": "华为新品 HUAWEI nova 4",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "【千玺代言】华为新品 HUAWEI nova 4 极点全面屏手机 4800万超广角三摄 8GB+128GB 亮黑色 全网通双卡双待",
              "proselectiontext":"0.45kg/件,空灰亮色，4800万",
              "payinfo":"",
              "currency":"￥",
              "uprice":"3399",
              "sevice":"选择增值服务",
              "promotioninf":""
            },
            {
              "id": 9,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s316x316_jfs/t27082/106/1022523438/480744/6c0735d5/5bbf19fdN647d5dd8.jpg!q70.dpg.webp",
              "producbrand": "HUAWEI",
              "producmodel": "华为 HUAWEI Mate 20 Pro",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "华为 HUAWEI Mate 20 Pro (UD)屏内指纹版麒麟980芯片全面屏超大广角徕卡三摄8GB+128GB翡冷翠全网通双4G手机",
              "proselectiontext":"0.5kg/件,翡冷翠,标准版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"5999",
              "sevice":"选择增值服务",
              "promotioninf":"选择增值服务"
            },
            {
              "id": 10,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t25954/134/1930444050/488286/31587d0d/5bbf1fc9N3ced3749.jpg!q70.dpg.webp",
              "producbrand": "HUAWEI",
              "producmodel": "华为 HUAWEI Mate 20",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "华为 HUAWEI Mate 20 麒麟980AI智能芯片全面屏超微距影像超大广角徕卡三摄6GB+128GB亮黑色全网通版双4G手机",
              "proselectiontext":"0.51kg/件，亮黑色，标准版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"4499",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":"买1件可优惠换购热销商品"
            },	
            {
              "id": 11,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t26038/101/1750775983/176935/5976cd0b/5bbc6e6fN5216f959.jpg!q70.dpg.webp",
              "producbrand": "HUAWEI",
              "producmodel": "华为 HUAWEI 畅享9 Plus",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "华为 HUAWEI 畅享9 Plus 4GB+64GB 幻夜黑 全网通 四摄超清全面屏大电池 移动联通电信4G手机 双卡双待",
              "proselectiontext":"0.5kg/件，幻黑色，标准版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"1380",
              "sevice":"选择增值服务",
              "promotioninf":""
            },
            {
              "id": 12,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t26038/101/1750775983/176935/5976cd0b/5bbc6e6fN5216f959.jpg!q70.dpg.webp",
              "producbrand": "HUAWEI",
              "producmodel": "华为 HUAWEI P20",
              "produsize": "",
              "productname": "智能手机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "华为 HUAWEI P20 AI智慧徕卡双摄全面屏游戏手机 6GB+64GB 极光色 全网通移动联通电信4G手机 双卡双待",
              "proselectiontext":"0.48kg/件，极光色，标准版",
              "payinfo":"",
              "currency":"￥",
              "uprice":"3188",
              "sevice":"选择增值服务",
              "promotioninf":""
            },
            {
              "id": 13,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t1/19859/28/5775/101767/5c418ae5Ef633541c/2f0678fab3b04773.jpg!q70.dpg.webp",
              "producbrand": "漫步者（EDIFIER）",
              "producmodel": "漫步者（EDIFIER）W200BT经典版",
              "produsize": "",
              "productname": "耳机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "漫步者（EDIFIER）W800BT 立体声蓝牙耳机  头戴式 苍穹黑",
              "proselectiontext":"0.42kg/件，W800BT",
              "payinfo":"",
              "currency":"￥",
              "uprice":"199",
              "sevice":"选择增值服务",
              "promotioninf":""
            },
            {
              "id": 14,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t3871/193/501637202/67656/c6725c75/58534587N53c62548.jpg!q70.dpg.webp",
              "producbrand": "苹果(APPLE)",
              "producmodel": "Apple  AirPods 蓝牙无线耳机",
              "produsize": "",
              "productname": "耳机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "Apple  AirPods 蓝牙无线耳机",
              "proselectiontext":"0.18kg/件，AirPods(蓝牙)",
              "payinfo":"",
              "currency":"￥",
              "uprice":"1276",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":""
            },
            {
              "id": 15,
              "selltype":"self",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s117x117_jfs/t1/14421/28/159/80563/5c07760bE4ad55d97/d42556fe36ea1e3b.jpg!q70.dpg.webp",
              "producbrand": "三星（SAMSUNG）",
              "producmodel": "三星（SAMSUNG）Gear IconX 2018升级款",
              "produsize": "",
              "productname": "耳机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "三星（SAMSUNG）Gear IconX 2018升级款",
              "proselectiontext":"0.7kg/件",
              "payinfo":"",
              "currency":"￥",
              "uprice":"1999",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":""
            },
            {
              "id": 16,
              "selltype":"self",
              "imgUrl": "https://img13.360buyimg.com/n2/s240x240_jfs/t17365/185/2637278968/111345/23fc829a/5b03af68Ne4180a01.jpg!q70.jpg",
              "producbrand": "索尼（SONY）WI-1000X",
              "producmodel": "索尼（SONY）WI-1000X Hi-Res颈挂式",
              "produsize": "",
              "productname": "耳机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "索尼（SONY）WI-1000X Hi-Res颈挂式 入耳式 无线蓝牙耳机 降噪耳机 手机通话 黑色",
              "proselectiontext":"0.6kg/件，黑色，颈挂式",
              "payinfo":"",
              "currency":"￥",
              "uprice":"1599",
              "sevice":"选择增值服务",
              "promotioninf":""
            },
            {
              "id": 17,
              "selltype":"self",
              "imgUrl": "https://img12.360buyimg.com/mobilecms/s316x316_jfs/t1/2114/25/13382/79229/5bd6dabdE39a28897/c9bc15728688520c.jpg!q70.dpg.webp",
              "producbrand": "Bose QuietControl 30",
              "producmodel": "Bose QuietControl 30",
              "produsize": "",
              "productname": "耳机",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "Bose QuietControl 30 无线耳机 QC30耳塞式蓝牙降噪耳麦",
              "proselectiontext":"",
              "payinfo":"",
              "currency":"￥",
              "uprice":"1599",
              "sevice":"选择增值服务(包含礼品服务)",
              "promotioninf":""
            }
    
          ],
          "united":[
            {
              "id": 4,
              "selltype":"united",
              "imgUrl": "https://img10.360buyimg.com/mobilecms/s168x168_jfs/t17095/164/1091901945/309628/8eec873e/5aba115aN583666cb.jpg!q70.dpg.webp",
              "producbrand": "清风（APP）",
              "producmodel": "原木纯品金装系列",
              "produsize": "3层120抽软抽纸巾*10包",
              "productname": "抽纸",
              "productcolor":"",
              "producotherinfo":"",
              "manufacutuer":"",
              "productbrief": "清风（APP）抽纸 原木纯品金装系列 3层120抽软抽纸巾*10包",
              "proselectiontext":"1.58kg/件，3层120抽纸巾*10包",
              "payinfo":"白条支付3期免息",
              "currency":"￥",
              "uprice":"24.9",
              "sevice":"",
              "promotioninf":"每满300减30元"
            }
          ]
        }
      }
    })
   // res.json(
   //   req.session.name
   // )
})

module.exports = router;
